### ISSUE TITLE
Increase font Lighting (Phone Territory)

### ISSUE THREAD

**Issue by JorgeMurilloJr** [Jordan-Davila/terribooks#8]
The font lighting on the names is a little too light. In addition, the font lighting for the placeholder "Name", that goes away once you start typing, is close to the name lighting. This request is mainly so as to be able to point out names easier and read them without having to focus too much (i.e zooming in, getting closer to the screen, etc.)

**Comment by Jordan-Davila** [comment]
I do plan on changing the color settings but for now, you can use the dark theme. To enable the dark theme, click on the switch icon located on the main menu.

**Comment by JorgeMurilloJr** [comment]
Nice! Didn't know it was already up.
